// ContentBrief is the central entity of the ideation pipeline.
// Generated by the engine's ideation service, then reviewed and acted on
// by the operator (accept → generate content, reject, or re-generate).
export interface ContentBrief {
  id: number;
  runId: string;
  rank: number;
  title: string;
  titleEn: string;
  templateType: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  cluster: string | null;
  rationale: string;
  dataSources: Record<string, boolean>;
  effort: string;
  urgency: string;
  score: number;
  provider: string;
  model: string;
  status: string;
  generatedPostSlug: string | null;
  createdAt: string;
  briefingText: string | null;
  briefingTextModel: string | null;
  templateInputs: Record<string, any> | null;
  pobUrl: string | null;
}

export type BriefStatus = 'all' | 'pending' | 'accepted' | 'rejected' | 'generated';
export type UrgencyFilter = 'all' | 'hot' | 'timely' | 'evergreen';

export interface BriefCounts {
  all: number;
  pending: number;
  accepted: number;
  rejected: number;
  generated: number;
}
