/**
 * Round-trip tests Part 1: placeholder helpers + serializer round-trips 1–6.
 *
 * Pattern:
 *   1. Build Tiptap JSON
 *   2. tiptapToPortable() → assert Portable Text shape
 *   3. portableToTiptap() → assert recovered structure matches original
 *
 * Keys (_key) are generated by nanoid and NOT asserted — correctness is
 * about structure + content, not stable IDs.
 *
 * Part 2 (round-trips 7–17 + PT→Tiptap): round-trip-2.test.ts
 */

import { describe, it, expect } from "vitest";
import { tiptapToPortable } from "../tiptap-to-portable";
import { portableToTiptap } from "../portable-to-tiptap";
import {
  formatPlaceholder,
  parsePlaceholders,
  splitByPlaceholders,
} from "../placeholders";
import {
  ttDoc,
  ttParagraph,
  ttHeading,
  ttBlockquote,
  ttBulletList,
  ttOrderedList,
  ttListItem,
  ttText,
  ttBold,
  ttItalic,
  ttLink,
} from "./fixtures";
import type { PortableTextBlock } from "@/lib/sanity/types";

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Strip _key fields so deep-equal ignores generated IDs. */
function stripKeys(val: unknown): unknown {
  if (Array.isArray(val)) return val.map(stripKeys);
  if (val && typeof val === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(val as Record<string, unknown>)) {
      if (k === "_key") continue;
      out[k] = stripKeys(v);
    }
    return out;
  }
  return val;
}

// ─── Placeholder helpers ──────────────────────────────────────────────────────

describe("placeholders: formatPlaceholder", () => {
  it("produces {{kind:value}} without modifier", () => {
    expect(formatPlaceholder("item", "Divine Orb")).toBe("{{item:Divine Orb}}");
  });

  it("produces {{kind:value|modifier}} with modifier", () => {
    expect(formatPlaceholder("price", "Chaos Orb", "chaos")).toBe("{{price:Chaos Orb|chaos}}");
  });

  it("preserves multi-word values with apostrophes", () => {
    expect(formatPlaceholder("item", "Kaom's Heart")).toBe("{{item:Kaom's Heart}}");
  });
});

describe("placeholders: parsePlaceholders", () => {
  it("parses a single placeholder", () => {
    const result = parsePlaceholders("{{item:Divine Orb}}");
    expect(result).toHaveLength(1);
    expect(result[0]).toMatchObject({ kind: "item", value: "Divine Orb", modifier: undefined });
  });

  it("parses placeholder with modifier", () => {
    const result = parsePlaceholders("{{price:Mageblood|poe2}}");
    expect(result[0]).toMatchObject({ kind: "price", value: "Mageblood", modifier: "poe2" });
  });

  it("parses multiple sequential placeholders in one string", () => {
    const result = parsePlaceholders("{{item:Divine Orb}} and {{price:Chaos Orb|chaos}}");
    expect(result).toHaveLength(2);
    expect(result[0].kind).toBe("item");
    expect(result[1].kind).toBe("price");
  });

  it("allows spaces in value (regression: multi-word names)", () => {
    const result = parsePlaceholders("{{item:Divine Orb}}");
    expect(result[0].value).toBe("Divine Orb");
  });

  it("does NOT match plain text without placeholder syntax", () => {
    expect(parsePlaceholders("just plain text")).toHaveLength(0);
  });

  it("does NOT false-match curly braces that aren't placeholders", () => {
    expect(parsePlaceholders("{item:Divine Orb}")).toHaveLength(0);
    expect(parsePlaceholders("{{Divine Orb}}")).toHaveLength(0);
  });
});

describe("placeholders: splitByPlaceholders", () => {
  it("returns a single text segment when no placeholders", () => {
    const segs = splitByPlaceholders("hello world");
    expect(segs).toHaveLength(1);
    expect(segs[0]).toEqual({ type: "text", text: "hello world" });
  });

  it("splits text around a single placeholder", () => {
    const segs = splitByPlaceholders("Buy {{item:Divine Orb}} now");
    expect(segs).toHaveLength(3);
    expect(segs[0]).toEqual({ type: "text", text: "Buy " });
    expect(segs[1].type).toBe("placeholder");
    expect(segs[2]).toEqual({ type: "text", text: " now" });
  });

  it("handles multiple sequential placeholders", () => {
    const segs = splitByPlaceholders("{{item:Orb A}}{{price:Orb B|chaos}}");
    expect(segs).toHaveLength(2);
    expect(segs.every((s) => s.type === "placeholder")).toBe(true);
  });
});

// ─── Round-trip 1: empty doc ──────────────────────────────────────────────────

describe("round-trip: 1 — empty doc", () => {
  it("serializes empty doc to empty blocks and back", () => {
    const doc = ttDoc();
    const pt = tiptapToPortable(doc);
    expect(pt).toHaveLength(0);

    const back = portableToTiptap(pt);
    expect(back).toEqual({ type: "doc", content: [] });
  });
});

// ─── Round-trip 2: plain paragraph ───────────────────────────────────────────

describe("round-trip: 2 — single paragraph plain text", () => {
  it("converts paragraph with plain text", () => {
    const doc = ttDoc(ttParagraph(ttText("Hello, World!")));
    const pt = tiptapToPortable(doc);

    expect(pt).toHaveLength(1);
    const block = pt[0] as PortableTextBlock;
    expect(block._type).toBe("block");
    expect(block.style).toBe("normal");
    expect(block.children[0].text).toBe("Hello, World!");
    expect(block.children[0].marks).toEqual([]);

    const back = portableToTiptap(pt);
    expect(stripKeys(back)).toEqual(stripKeys(doc));
  });
});

// ─── Round-trip 3: bold + italic + link ──────────────────────────────────────

describe("round-trip: 3 — paragraph with bold + italic + link", () => {
  it("converts rich inline marks", () => {
    const doc = ttDoc(
      ttParagraph(
        ttBold("bold text"),
        ttText(" "),
        ttItalic("italic text"),
        ttText(" "),
        ttLink("click here", "https://example.com", true),
      ),
    );

    const pt = tiptapToPortable(doc);
    const block = pt[0] as PortableTextBlock;

    const boldSpan = block.children.find((c) => c.text === "bold text");
    expect(boldSpan?.marks).toContain("strong");

    const italicSpan = block.children.find((c) => c.text === "italic text");
    expect(italicSpan?.marks).toContain("em");

    const linkSpan = block.children.find((c) => c.text === "click here");
    expect(linkSpan?.marks).toHaveLength(1);
    const linkDefKey = linkSpan!.marks[0];
    const linkDef = block.markDefs.find((d) => d._key === linkDefKey);
    expect(linkDef?._type).toBe("link");
    expect((linkDef as { href: string }).href).toBe("https://example.com");

    const back = portableToTiptap(pt);
    const backBlock = back.content?.[0] as { type: string; content: unknown[] };
    expect(backBlock.type).toBe("paragraph");
    expect(backBlock.content).toHaveLength(5);
  });
});

// ─── Round-trip 4: headings ───────────────────────────────────────────────────

describe("round-trip: 4 — headings h1 through h4", () => {
  it("converts all heading levels", () => {
    const doc = ttDoc(
      ttHeading(1, ttText("H1")),
      ttHeading(2, ttText("H2")),
      ttHeading(3, ttText("H3")),
      ttHeading(4, ttText("H4")),
    );

    const pt = tiptapToPortable(doc);
    expect(pt).toHaveLength(4);

    const styles = (pt as PortableTextBlock[]).map((b) => b.style);
    expect(styles).toEqual(["h1", "h2", "h3", "h4"]);

    const back = portableToTiptap(pt);
    const levels = (back.content ?? []).map(
      (n) => (n as { attrs: { level: number } }).attrs?.level,
    );
    expect(levels).toEqual([1, 2, 3, 4]);
  });

  it("caps heading level at h4", () => {
    // Tiptap allows h5/h6 but Sanity blockContent schema caps at h4
    const doc = ttDoc(ttHeading(5, ttText("Too deep")));
    const pt = tiptapToPortable(doc);
    expect((pt[0] as PortableTextBlock).style).toBe("h4");
  });
});

// ─── Round-trip 5: blockquote ────────────────────────────────────────────────

describe("round-trip: 5 — blockquote with rich text", () => {
  it("converts blockquote with bold content", () => {
    const doc = ttDoc(
      ttBlockquote(ttParagraph(ttBold("quoted"), ttText(" text"))),
    );

    const pt = tiptapToPortable(doc);
    expect((pt[0] as PortableTextBlock).style).toBe("blockquote");

    const back = portableToTiptap(pt);
    const node = back.content?.[0] as { type: string };
    expect(node.type).toBe("blockquote");
  });
});

// ─── Round-trip 6: lists ─────────────────────────────────────────────────────

describe("round-trip: 6 — bullet list, numbered list, nested", () => {
  it("converts flat bullet list", () => {
    const doc = ttDoc(
      ttBulletList(
        ttListItem(ttParagraph(ttText("Item 1"))),
        ttListItem(ttParagraph(ttText("Item 2"))),
      ),
    );

    const pt = tiptapToPortable(doc);
    expect(pt).toHaveLength(2);
    const blocks = pt as PortableTextBlock[];
    expect(blocks[0].listItem).toBe("bullet");
    expect(blocks[1].listItem).toBe("bullet");
    expect(blocks[0].level).toBe(1);

    const back = portableToTiptap(pt);
    const list = back.content?.[0] as { type: string; content: unknown[] };
    expect(list.type).toBe("bulletList");
    expect(list.content).toHaveLength(2);
  });

  it("converts flat ordered list", () => {
    const doc = ttDoc(
      ttOrderedList(
        ttListItem(ttParagraph(ttText("First"))),
        ttListItem(ttParagraph(ttText("Second"))),
      ),
    );

    const pt = tiptapToPortable(doc);
    const blocks = pt as PortableTextBlock[];
    expect(blocks[0].listItem).toBe("number");
    expect(blocks[1].listItem).toBe("number");

    const back = portableToTiptap(pt);
    const list = back.content?.[0] as { type: string };
    expect(list.type).toBe("orderedList");
  });

  it("converts nested list (bullet inside bullet)", () => {
    const doc = ttDoc(
      ttBulletList(
        ttListItem(
          ttParagraph(ttText("Parent")),
          ttBulletList(ttListItem(ttParagraph(ttText("Child")))),
        ),
      ),
    );

    const pt = tiptapToPortable(doc);
    // Both parent and child become separate PT blocks with different levels
    const blocks = pt as PortableTextBlock[];
    expect(blocks.some((b) => (b.level ?? 1) === 1)).toBe(true);
    expect(blocks.some((b) => (b.level ?? 1) === 2)).toBe(true);
  });
});
